version: '3.8'

services:
  # 1. The Backend Service
  server:
    build:
      context: ./server
      dockerfile: DockerFile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI="mongodb+srv://user:userpass@cluster0.3z7qbix.mongodb.net/?appName=Cluster0:""
      - GEMINI_API_KEY=AIzaSyB423fdE_zqYnOQ-zIq0jWNcXy1sgPNtvQ
    networks:
      - app-network

  # 2. The Frontend Service
  client:
    build:
      context: ./client
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    stdin_open: true # Keeps the React app running interactively
    environment:
      - CHOKIDAR_USEPOLLING=true # Enables hot-reloading inside Docker
    depends_on:
      - server # Wait for the backend to start first
    networks:
      - app-network

networks:
  app-network:
    driver: bridge